apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: host-root
      mountPath: /host-root
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
  restartPolicy: Never
