apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-home-sa
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa
  namespace: development
