apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sReadOnlyFSNoHostPath
metadata:
  name: require-readonly-fs-no-hostpath
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "audit-zone"
  parameters:
    message: "Требуется readOnlyRootFilesystem: true и запрещён hostPath"