apiVersion: constraints.gatekeeper.sh/v1
kind: K8sPSPRunAsNonRoot
metadata:
  name: require-run-as-non-root
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "audit-zone"
  parameters:
    message: "Все Pod должны запускаться не от root пользователя (runAsNonRoot: true)"