---
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  - level: RequestResponse
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""
        resources:
          - "pods"
          - "secrets"
          - "configmaps"
          - "serviceaccounts"
      - group: "rbac.authorization.k8s.io"
        resources:
          - "roles"
          - "rolebindings"
          - "clusterroles"
          - "clusterrolebindings"
  - level: RequestResponse
    verbs: ["create"]
    resources:
      - group: ""
        resources:
          - "pods/exec"
          - "pods/attach"
          - "pods/portforward"
  - level: Metadata
    verbs: ["get", "list"]
    resources:
      - group: ""
        resources:
          - "secrets"
          - "configmaps"
  - level: Metadata
